# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QFileDialog
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
from matplotlib import pyplot as plt
import xlsxwriter

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(869, 201)
        font = QtGui.QFont()
        font.setPointSize(18)
        Form.setFont(font)
        self.horizontalLayoutWidget = QtWidgets.QWidget(Form)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(80, 100, 277, 51))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.z1 = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.z1.setFont(font)
        self.z1.setObjectName("z1")
        self.horizontalLayout.addWidget(self.z1)
        self.label_2 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.z2 = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.z2.setFont(font)
        self.z2.setObjectName("z2")
        self.horizontalLayout.addWidget(self.z2)
        self.label_3 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_3.setFont(font)
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.run = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.run.setFont(font)
        self.run.setObjectName("run")
        self.horizontalLayout.addWidget(self.run)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(Form)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(78, 52, 711, 41))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_4 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        self.filename = QtWidgets.QTextEdit(self.horizontalLayoutWidget_2)
        self.filename.setObjectName("filename")
        self.horizontalLayout_2.addWidget(self.filename)
        self.btn_load = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.btn_load.setObjectName("btn_load")
        self.horizontalLayout_2.addWidget(self.btn_load)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

         # Bind ui function
        self.btn_load.clicked.connect(self.loadFile)
        self.run.clicked.connect(self.runNDL)

    def loadFile(self):
        self.excelPath = QFileDialog.getOpenFileName(filter="Excel File (*.xlsx *.xls)")[0]
        print(self.excelPath)
        self.filename.setText(self.excelPath)      
        df = pd.read_excel(self.excelPath, 0)
        Z_Group = df.iloc[:, 4].transpose()               
        self.z1.setText(str(Z_Group[0]))
        self.z2.setText(str(Z_Group[Z_Group.size - 1]))


    def linear_regression(self, x, y):     
        N = len(x)
        x_mean = x.mean()
        y_mean = y.mean()
        
        B1_num = ((x - x_mean) * (y - y_mean)).sum()
        B1_den = ((x - x_mean)**2).sum()
        B1 = B1_num / B1_den
        
        B0 = y_mean - (B1*x_mean)
        
        reg_line = 'y = {} + {}β'.format(B0, B1)
        return (B0, B1, reg_line)

    def runNDL(self):         
        df = pd.read_excel(self.excelPath, 0)
        df_na = df.dropna(axis=1)
       
        x = np.array(df.iloc[:,2].dropna(how='all').tolist()).transpose() * np.expm1(1e-6)
        xnums = x.size # AC_Level nums
        gnums = int( (df_na.shape[1] - 1) / xnums )  # group nums , shape[1] = columes nums   
        Z_Group = df.iloc[:, 4].transpose()         
                
        z_start = (Z_Group.tolist().index(float(self.z1.text())))        
        z_end = (Z_Group.tolist().index(float(self.z2.text())))
        
        g_df1 = pd.DataFrame(0, index=range(z_end + 1), columns=range(1 + gnums * 4))
        g_df2 = pd.DataFrame(0, index=range(z_end + 1), columns=range(1 + gnums * 2))
        g_df1[0] = Z_Group[0:z_end+1] 
        g_df2[0] = Z_Group[0:z_end+1]

        for m in range(gnums):            
            XY_Transpose = df.iloc[:, (5 + xnums * m):(5 + xnums * (m+1))].transpose() # G1
            print(XY_Transpose)
            #x = (np.array([25, 50, 75, 100, 150, 200, 250]).transpose() * np.expm1(1e-6)).reshape((-1, 1))         
            x = x.reshape((-1, 1))  


            # Step2 -> Regression Line
            # Sheet 1           
            for n in range(z_end+1):     
                       
                y = XY_Transpose.iloc[:, [n]].to_numpy() # 0 = Y1        
                C0, C1, reg_line = self.linear_regression(x, y)
                # print('Regression Line: ', reg_line)
                # print('C0 = ' , C0)
                # print('C1 = ', C1)
                # print('Z = ', Z_Group[n] )

                # Step3 -> Parameter cal.
                q = 1.60217663 * 1e-19     
                E0 = 8.854187817 * 1e-12  
                Es = df.iloc[:,0][0]
                A = df.iloc[:,1][0]

                NDL = - (C0 ** 3) / (2 * q * E0 * Es * (A ** 2) * C1) 
                d = (E0 * Es * A) / C0    
                g_list1 = [C1, C0, NDL, d]
                g_list2 = [NDL, d]                
                # print('Z = ', Z_Group[n] )            
                # print('C1 = ', C1)
                # print('C0 = ' , C0)
                # print('NDL = ', NDL)
                # print('d = ', d)
                g_df1.loc[n, 1+4*m:4*(m+1)] = g_list1       
                g_df2.loc[n, 1+2*m:2*(m+1)] = g_list2
                
    
        print(g_df1)
        print(g_df2)
        with pd.ExcelWriter('output.xlsx') as writer:
            g_df1.to_excel(writer, sheet_name='sheet1')
            g_df2.to_excel(writer, sheet_name='sheet2')      

  
       
    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "VBias"))
        self.label_2.setText(_translate("Form", "~"))
        self.run.setText(_translate("Form", "run"))
        self.label_4.setText(_translate("Form", "Excel File :"))
        self.btn_load.setText(_translate("Form", "Load"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    NDL_D = QtWidgets.QMainWindow()
    ui = Ui_Form()
    ui.setupUi(NDL_D)
    NDL_D.show()
    sys.exit(app.exec_())        